### ISSUE TITLE
XML (zip) origin

### ISSUE THREAD

**Issue by guy-keller** [crystalmark/tides#2]
Hello there, 

Where did you get the constituents.xml and stations.xml from? 
The ones that are in the zip file I mean.

I am making this into a standalone lib 😃 

Cheers!

**Comment by crystalmark** [comment]
Hi!  I can't remember, it was soooo long ago.  It could have been Admiralty Solutions: https://admiraltyapi.portal.azure-api.net/ or NOAA: https://tidesandcurrents.noaa.gov/web_services_info.html. Let me know how you get on with the lib, I'd be interested in using it.

**Comment by guy-keller** [comment]
Hi @crystalmark,

Have a look at the code here:
https://github.com/guikeller/tides

If you are happy with that I am happy to send a PR to you.
So you could merge back in and retain the ownership of it all.

Only suggestion is to change the package names to something more like:
``` java 
package com.github.jtides;
```
Is that okay with you?

Thanks! 👍

**Comment by crystalmark** [comment]
Thanks - I'm totally happy with you taking credit for the lib stuff, you've done lots of clean-up and improvements.  I'm also happy if you wanted to change the package to com.github.jtides and PR to keep it in the original repo.  I plan to continue with the https://github.com/crystalmark/boatcam project soon (which uses the tides stuff) after I've completed some of the other lockdown projects!

**Comment by guy-keller** [comment]
I have created the PR so you can bring the changes in whenever; also, there are no merge conflicts.
Good luck with the rest of the projects, I did find a little bug and will raise a new issue for better traceability.

Feel free to merge / and close this issue.

**Comment by guy-keller** [comment]
I've used the lib here: https://github.com/guikeller/open-tides
